title: kinyou_benkyokai
description: > # 金曜にする勉強会です
  やりたいことをやりたいときにやりたいだけやってそれを教えたいときに誰かにおしえる
baseurl: "/docs/" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lailaiskyn
github_username:  shiv3

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
